### ISSUE TITLE
Homepage - Console Error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#1]
![image](https://cloud.githubusercontent.com/assets/12888048/9376982/b2879052-4746-11e5-8a5c-ac09ca8f561f.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9513437/c454bea0-4cc2-11e5-8a2f-6932b876152a.png)

**Comment by christiancebudigital** [comment]
Please clear your cache.. no error found on our end...

**Comment by romatitan** [comment]
I've cleared the cache and check again the console.

Chrome - console error: Falied to load resource: net::ERR_BLOCKED_BY_CLIENT
The error still occurs at my end, but I've tried to check with other PC and chrome-browser and there's no error occurs.
Result: 1:3

But still a console error occurs in IE browsers.
IE - console error: SCRIPTS: Access is denied.
Result: 3:3
![image](https://cloud.githubusercontent.com/assets/12888048/9538525/26c0407c-4d78-11e5-93f5-26436d6775e9.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

No error on our end see attached screenshot, will verify this with bernard, as this  not going to be fixed if you have error on your pc,
![ie](https://cloud.githubusercontent.com/assets/11186331/9593706/a15b0a24-5084-11e5-861f-dd733584e7fa.jpg)


Thanks,
Christian

**Comment by romatitan** [comment]
I've checked this issue with other QA and dev PC.
Verified fixed.
Result 0:3
