### ISSUE TITLE
Sitemap: Console Error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#10]
![image](https://cloud.githubusercontent.com/assets/12888048/9377053/607ac1ca-4747-11e5-8c31-5c1c14aabd8a.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9513537/bbabb924-4cc3-11e5-8c0b-f43b55540aa6.png)

**Comment by christiancebudigital** [comment]
Please clear your cache.. no error found on our end...

**Comment by romatitan** [comment]
I've cleared the cache and check again the console.

Chrome - console error: Falied to load resource: net::ERR_BLOCKED_BY_CLIENT
The error still occurs at my end, but I've tried to check with other PC and chrome-browser and there's no error occurs.
Result: 1:3
For chrome browser its won't fix.

But still a console error occurs in IE browsers.
IE - console error: SCRIPTS: Access is denied.
Result: 3:3
![image](https://cloud.githubusercontent.com/assets/12888048/9538579/9485921a-4d78-11e5-97ba-15ef7f84076c.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

No error on our end see attached screenshot, will verify this with bernard, as this not going to be fixed if you have error on your pc,
![ie](https://cloud.githubusercontent.com/assets/11186331/9593723/dbee7b26-5084-11e5-9d3e-1a55b64593fe.jpg)

**Comment by romatitan** [comment]
I've checked this issue with other QA and dev PC.
Verified fixed.
Result 0:3
