### ISSUE TITLE
Clarification: At the left side of the header, it has contact icons, same with what the project scope has stated. But in the new design version, 01b-BNT-Home, there's none. Kindly check the new design version, clarify with leads and update the scope accordingly.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#13]
![image](https://cloud.githubusercontent.com/assets/12888048/9377505/4e0841ca-474c-11e5-83cf-27668cc7e10c.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

I have updated the scope, you may now verify the site by clicking this link.

Thanks,
Christian
