### ISSUE TITLE
Footer: Incorrect footer option (#8) implemented. It should be option#2

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#17]
Reference: SEO footer option # 2
https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking

![image](https://cloud.githubusercontent.com/assets/12888048/9377784/bbd4fc3c-474e-11e5-9959-d60876688640.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9377789/c6dbdd62-474e-11e5-95b5-0d1d0ac5ef72.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

I have updated the Project scope, #8 is the closest seo footer to be matched in the design.

Thanks,
Christian
