### ISSUE TITLE
Clarification: For lead-ins, It stated in the project scope,"icon image ACF - required", Yet it was not implemented instead custom post featured image was used. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#21]
Clarify with leads and update the scope accordingly. Thanks

![image](https://cloud.githubusercontent.com/assets/12888048/9378349/5c106a66-4753-11e5-95cd-146551f7e89c.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9378454/2bab9dd6-4754-11e5-9fd0-2492f1585f57.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

I've updated the scope you may now verify the site.

Thanks,
Christian

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9513292/eeaa07ca-4cc0-11e5-89db-d6c9e1634e92.png)
