### ISSUE TITLE
Admin - FAQ: Nested repeater wasn't implemented. It should have, Nested repeater acf ( -  first repeater acf [ label acf, textarea acf ] ) and (  - - second repeater [ label acf, file acf ] ) as state in the project scope

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#24]
![image](https://cloud.githubusercontent.com/assets/12888048/9378844/380a7bbc-4757-11e5-990e-a8028d1d387b.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

I have updated, the project scope, you may now verify it at your end.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi Christian,

Kindly check again the project scope.
It seems that the FAQ ACF wasn't updated.

![image](https://cloud.githubusercontent.com/assets/12888048/9514151/1bf15464-4cca-11e5-838b-94c2eb842537.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

thanks for that :D, project acf has been updated.

Cheers,
Christian
