### ISSUE TITLE
About Us: Console Error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#3]
![image](https://cloud.githubusercontent.com/assets/12888048/9376990/ccea8e9a-4746-11e5-9bbf-b7c7cc1c33c9.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9513485/3e75a3ac-4cc3-11e5-82c2-3072eb357751.png)

**Comment by christiancebudigital** [comment]
Please clear your cache.. no error found on our end...

**Comment by romatitan** [comment]
I've cleared the cache and check again the console.

Chrome - console error: Falied to load resource: net::ERR_BLOCKED_BY_CLIENT
The error still occurs at my end, but I've tried to check with other PC and chrome-browser and there's no error occurs.
Result: 1:3
I'll label this as won't fix

**Comment by christiancebudigital** [comment]
Hi Roma,

No error on our end see attached screenshot, will verify this with bernard, as this is not going to be fixed if you have error on your pc.

Thanks,
Christian

**Comment by romatitan** [comment]
I've checked this issue with other QA and dev PC.
Verified fixed.
Result 0:3
