### ISSUE TITLE
Clarification - Services: A page with anchor link should not have a pagination because there will be a conflict with the two functions.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#35]
Related question #39
Please clarify with leads and update the scope accordingly.
![image](https://cloud.githubusercontent.com/assets/12888048/9431605/56846e2a-4a47-11e5-8910-b902a8fef232.png)

**Comment by romatitan** [comment]
As per Bernand said, there should be no pagination if there's an anchor link.
Kindly update the scope accordingly. Thanks.

**Comment by christiancebudigital** [comment]
Hi  Roma,

We have updated the project scope, please verify.

Thanks,
Christian
