### ISSUE TITLE
Clarification : Services - Sidebar: The used of an anchor link was not mentioned in the project scope but shown in the given design and implemented on the sidebar. Should it have an anchor link or read more link?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#39]
Related question #35 
Please clarify with leads and update the scope accordingly.

![image](https://cloud.githubusercontent.com/assets/12888048/9431878/34d68cc2-4a4c-11e5-84bd-bb994646522c.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9432211/950c6a26-4a51-11e5-9af0-e3a3f109654b.png)

**Comment by genesiscebudigital** [comment]
It is anchor link
