### ISSUE TITLE
News: Pagination implemented was different from what the design has

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#49]
![image](https://cloud.githubusercontent.com/assets/12888048/9432341/1c97d276-4a54-11e5-939b-334e346ec67d.png)

**Comment by genesiscebudigital** [comment]
It is better to make consistent

**Comment by romatitan** [comment]
Reference issue #47

![image](https://cloud.githubusercontent.com/assets/12888048/9514754/5dd2d588-4ccf-11e5-8502-9ca90b5b8d45.png)
