### ISSUE TITLE
Clarification: Admin - Custom Fields: "Contact Us Form" should be included in custom fields or in option/global fields?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#55]
![image](https://cloud.githubusercontent.com/assets/12888048/9432652/a3817234-4a58-11e5-85c8-a47cfd94559f.png)

**Comment by genesiscebudigital** [comment]
this is defualt in the titan theme

**Comment by christiancebudigital** [comment]
Hi Roma,

The purpose of this field found in contact us page, is for us user to update the gravity form shortcode  dynamically without touching the files, hopefully this makes sense :D.

Thanks,
Christian
