### ISSUE TITLE
News: On the next page, Lead-ins top and bottom custom post were missing

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#58]
Go to next page (or page 2)
![image](https://cloud.githubusercontent.com/assets/12888048/9433729/1a121790-4a69-11e5-9e5d-02bafb33e1db.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9538924/adad3cc6-4d7c-11e5-95ab-26f6bace711a.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

Please see attached screenshot.

Thanks,
Christian
![nt-legal-news](https://cloud.githubusercontent.com/assets/11186331/9598506/cf89ad30-50be-11e5-88e7-bc2687cfcea4.jpg)

**Comment by romatitan** [comment]
Hi Christian,
Its not about I "have issue with my pc".
I verify this bug with other QA pc and even with the other dev here.
As I have mentioned with the issue title,
" Abouts: On the next page, Lead-ins TOP and BOTTOM custom post were missing"
And still, the lead-ins bottom custom post was missing.
Kindly check again.

Please see attached screenshot.
![image](https://cloud.githubusercontent.com/assets/12888048/9620321/9321ddb2-514b-11e5-9d5b-4856a7809a21.png)


Thanks,
Roma
