### ISSUE TITLE
Testimonials: On the next page, Lead-ins top and bottom custom post were missing

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#59]
Go to next page (or page 2)
![image](https://cloud.githubusercontent.com/assets/12888048/9433733/2ca2d3cc-4a69-11e5-9e02-4e3b1c7301c8.png)

**Comment by genesiscebudigital** [comment]
clear the cache

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9538959/0674a5ba-4d7d-11e5-81f4-a6a1b9297d95.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

please see attached screenshot.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi Christian,
Its not about I "have issue with my pc".
I verify this bug with other QA pc and even with the other dev here.
As I have mentioned with the issue title,
" Abouts: On the next page, Lead-ins TOP and BOTTOM custom post were missing"
And still, the lead-ins bottom custom post was missing.
Kindly check again.

Please see attached screenshot.
![image](https://cloud.githubusercontent.com/assets/12888048/9620320/8ad1942c-514b-11e5-8bb8-d4e30abe838d.png)


Thanks,
Roma
