### ISSUE TITLE
Abouts: On the next page, Lead-ins top and bottom custom post were missing

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#60]
Go to next page (or page 2)
![image](https://cloud.githubusercontent.com/assets/12888048/9433737/37dcf3bc-4a69-11e5-8871-981b6f6bf6eb.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9538956/003a9ae2-4d7d-11e5-866f-500d7d1501b4.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

This is working on our end,  please clear cache, i think you have issue on your pc, please see attached screen shot.

Thanks,
Christian
![bnt-legal-about](https://cloud.githubusercontent.com/assets/11186331/9598455/3da571b0-50be-11e5-8135-1f9036446e3a.jpg)

**Comment by romatitan** [comment]
Hi Christian,
Its not about I "have issue with my pc".
I verify this bug with other QA pc and even with the other dev here.

Bottom custom post are still missing.
Kindly check again.
Please see attached screenshot.
![image](https://cloud.githubusercontent.com/assets/12888048/9620253/d473b5ca-514a-11e5-8e59-16b78b4f7279.png)
