### ISSUE TITLE
General - Banner: Because an error occurs and need to click the play button to continue, after clicking the button, the navigation arrow was no longer display in the banner

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#70]
Affected browser: IE9

![image](https://cloud.githubusercontent.com/assets/12888048/9435580/a564a8dc-4a7b-11e5-9bd5-cb7443f530ea.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9435582/a8726a14-4a7b-11e5-8be9-642bdd05e42b.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9435584/ab61e18c-4a7b-11e5-87db-893dc0a91d08.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/9515257/c95d8bf6-4cd2-11e5-88c4-15ea33379b90.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9515277/e9d42da4-4cd2-11e5-8b49-f4f26e5d44d9.png)

**Comment by christiancebudigital** [comment]
this is fixed on our end. please clear cache ..thanks :D
![bnt-legal](https://cloud.githubusercontent.com/assets/11186331/9598232/193abcb0-50bc-11e5-9657-088f69635f15.jpg)
