### ISSUE TITLE
Services - sidebar: Enquire now button has no function to call.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#76]
![image](https://cloud.githubusercontent.com/assets/12888048/9515750/002161a0-4cd6-11e5-8a9d-070c2fa543cb.png)

**Comment by christiancebudigital** [comment]
added new acf field in services and updated the project scope.

**Comment by romatitan** [comment]
Page link was added.
Enquire Now button, once click it will link to the Contact page.
