### ISSUE TITLE
Header: Contact icon wasn't aligned with the contact numbers. Email address wasn't aligned to center

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/BNT-Legal#91]
Affected device(s): S4, iPodtouch5, iPadair

![image](https://cloud.githubusercontent.com/assets/12888048/9541375/1d21465c-4d9a-11e5-9967-af9f3c55e503.png)

![image](https://cloud.githubusercontent.com/assets/12888048/9541378/1f67da0c-4d9a-11e5-8152-c08d41f166ff.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

please clear cache it is working on our end.

Thanks,
Christian

**Comment by romatitan** [comment]
Hi,

I already cleared the cache.
But still, It's not yet fixed on S4, iPodtouch5, 

Thanks,
Roma

**Comment by romatitan** [comment]
The email address was aligned to left.
The error occurs in Homepage.
Affected devices: S4, iPodtouch5, iPadair

Please see attached screenshot.
![image](https://cloud.githubusercontent.com/assets/12888048/9647758/df56de0e-5212-11e5-89b8-368f16e2f8f4.png)
